const express = require('express')
const multer = require('multer')
const crypto = require('node:crypto')
const PDFDocument = require('pdfkit')
const database = require('./localDatabase')
const { companyConfig } = require('../config/companyConfig')
const { aggregateTaxInvoiceTotals } = require('../services/invoiceTotals')
const { calculateInvoice, financialYear } = require('../services/invoiceService')

const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024, files: 20 } })
const router = express.Router()
const demoUser = { id: 'demo-admin', email: 'demo@localhost.test', name: 'Demo Administrator' }
const clean = value => String(value ?? '').trim()

function localInvoiceNumber(billingEntity, invoiceType = 'tax_invoice', date = new Date().toISOString().slice(0, 10), offset = 1) {
  const configured = companyConfig.billing.entities.find(entity => entity.key === billingEntity) || companyConfig.billing.entities[0]
  const prefix = invoiceType === 'proforma_invoice' ? configured?.proformaPrefix : configured?.invoicePrefix
  const existing = database.list('invoices').filter(row => row.invoice_type === invoiceType && row.billing_entity === billingEntity).length
  return `${prefix || billingEntity || 'INV'}/${financialYear(date)}/${String(existing + offset).padStart(3, '0')}`
}

function renderLocalInvoice(invoice, entity) {
  return new Promise((resolve, reject) => {
    const document = new PDFDocument({ size: 'A4', margin: 48, info: { Title: invoice.invoice_number } })
    const chunks = []
    document.on('data', chunk => chunks.push(chunk))
    document.on('end', () => resolve(Buffer.concat(chunks)))
    document.on('error', reject)
    document.fontSize(22).text(invoice.invoice_type === 'proforma_invoice' ? 'PROFORMA INVOICE' : 'TAX INVOICE', { align: 'center' })
    document.moveDown().fontSize(11)
    document.text(`Invoice number: ${invoice.invoice_number}`)
    document.text(`Invoice date: ${invoice.invoice_date}`)
    document.moveDown()
    document.fontSize(14).text(entity.legal_entity_name || 'Local demo entity')
    document.fontSize(10).text(entity.address || '')
    document.text(`Consultant: ${invoice.consultant_name || '-'}`)
    document.text(`Candidate: ${invoice.candidate_name || '-'}`)
    document.moveDown()
    document.text(`Professional fee: INR ${Number(invoice.taxable_amount || 0).toFixed(2)}`)
    document.text(`Tax: INR ${Number(invoice.total_tax_amount || 0).toFixed(2)}`)
    document.fontSize(13).text(`Grand total: INR ${Number(invoice.grand_total || 0).toFixed(2)}`)
    document.moveDown(2).fontSize(9).fillColor('#666666').text('Generated by the local ATS demo. No external services were contacted.')
    document.end()
  })
}

async function localInvoiceResult(input, { persist = false } = {}) {
  const entity = database.get('invoice_entities', input.invoice_entity_id)
  if (!entity) throw new Error('Select a valid invoice entity.')
  const invoiceType = input.invoice_type === 'proforma_invoice' ? 'proforma_invoice' : 'tax_invoice'
  const billingEntity = input.billing_entity || entity.billing_entity || companyConfig.billing.entities[0]?.key
  const invoiceDate = input.invoice_date || new Date().toISOString().slice(0, 10)
  const calculated = calculateInvoice({ ...input, ...entity, billing_entity: billingEntity })
  const invoice = {
    ...input,
    ...calculated,
    id: input.id || crypto.randomUUID(),
    invoice_entity_id: entity.id,
    invoice_type: invoiceType,
    invoice_display_id: input.invoice_display_id || `IID${database.count('invoices') + 1}`,
    invoice_number: input.invoice_number || localInvoiceNumber(billingEntity, invoiceType, invoiceDate),
    invoice_date: invoiceDate,
    financial_year: financialYear(invoiceDate),
    sequence_number: database.count('invoices') + 1,
    billing_entity: billingEntity,
    status: input.status || 'active',
    pdf_versions: []
  }
  const saved = persist ? database.put('invoices', invoice) : invoice
  const pdf = await renderLocalInvoice(saved, entity)
  return { data: saved, pdfBase64: pdf.toString('base64'), fileName: `${saved.invoice_number.replaceAll('/', '-')}.pdf` }
}

function updateStored(kind, recordId, changes) {
  const current = database.get(kind, recordId)
  return current ? database.put(kind, { ...current, ...changes, id: recordId }) : null
}

function body(req) {
  const value = { ...req.body }
  for (const key of ['skills', 'consultants', 'public_skills', 'contract_attachments', 'cv_attachments']) {
    if (typeof value[key] !== 'string') continue
    try { value[key] = JSON.parse(value[key]) } catch { value[key] = value[key].split(',').map(clean).filter(Boolean) }
  }
  return value
}

function page(rows, req) {
  let values = [...rows]
  const search = clean(req.query.search).toLowerCase()
  if (search) values = values.filter(row => JSON.stringify(row).toLowerCase().includes(search))
  const pageNumber = Math.max(1, Number(req.query.page) || 1)
  const limit = Math.min(100, Math.max(1, Number(req.query.limit) || 50))
  const total = values.length
  return { data: values.slice((pageNumber - 1) * limit, pageNumber * limit), total, page: pageNumber, totalPages: Math.max(1, Math.ceil(total / limit)), limit }
}

function kindRoutes(kind, prefix, idField) {
  router.get(`/${kind}/next-display-id`, (req, res) => res.json({ [`${kind.slice(0, -1)}_display_id`]: database.displayId(prefix, kind) }))
  router.get(`/${kind}`, (req, res) => {
    const rows = database.list(kind)
    if (String(req.query.options).toLowerCase() === 'true' || String(req.query.all).toLowerCase() === 'true') return res.json({ data: rows })
    return res.json(page(rows, req))
  })
  router.get(`/${kind}/:id`, (req, res) => {
    const record = database.get(kind, req.params.id)
    return record ? res.json(record) : res.status(404).json({ error: `${kind.slice(0, -1)} not found` })
  })
  router.post(`/${kind}`, upload.any(), (req, res) => {
    const payload = body(req)
    payload.id ||= crypto.randomUUID()
    payload[idField] ||= database.displayId(prefix, kind)
    if (kind === 'jobs') {
      payload.title ||= payload.role
      payload.role ||= payload.title
      const client = database.get('clients', payload.client_id)
      payload.client_name ||= client?.client_name || client?.name || ''
      payload.mandate_status ||= payload.status || companyConfig.jobs.statuses[0]
      payload.status = payload.mandate_status
    }
    if (kind === 'clients') {
      payload.client_name ||= payload.name
      payload.name ||= payload.client_name
      payload.client_group_id ||= payload.id
    }
    if (kind === 'candidates') {
      payload.full_name ||= payload.candidate_name || payload.name
      payload.candidate_name ||= payload.full_name
      payload.associationId ||= crypto.randomUUID()
      payload.candidateId ||= crypto.randomUUID()
      payload.status ||= payload.candidate_status || companyConfig.pipeline.find(stage => stage.enabled)?.label || 'Interested'
      payload.candidate_status = payload.status
      const client = database.get('clients', payload.client_id)
      const job = database.get('jobs', payload.job_id)
      payload.client_name ||= client?.client_name || ''
      payload.job_title ||= job?.title || ''
    }
    return res.status(201).json(database.put(kind, payload))
  })
  router.patch(`/${kind}/:id`, upload.any(), (req, res) => {
    const existing = database.get(kind, req.params.id)
    if (!existing) return res.status(404).json({ error: `${kind.slice(0, -1)} not found` })
    return res.json(database.put(kind, { ...existing, ...body(req), id: req.params.id }))
  })
  router.delete(`/${kind}/:id`, (req, res) => database.remove(kind, req.params.id)
    ? res.json({ message: `${kind.slice(0, -1)} deleted successfully` })
    : res.status(404).json({ error: `${kind.slice(0, -1)} not found` }))
}

router.use((req, res, next) => {
  req.user = demoUser
  res.setHeader('x-ats-runtime', 'local-demo')
  next()
})

router.get('/health', (req, res) => res.json({ status: 'ok', runtime: 'local-demo', database: database.databasePath }))
router.get('/auth/me', (req, res) => res.json({ user: demoUser }))
router.get('/auth/employment-status', (req, res) => res.json({ data: { user_id: demoUser.id, profile_complete: true, status: 'active' } }))
router.get('/user-profiles', (req, res) => res.json({ data: database.get('profiles', demoUser.id) }))
router.post('/user-profiles', (req, res) => res.json({ data: database.put('profiles', { ...req.body, id: demoUser.id, user_id: demoUser.id, email: demoUser.email }) }))
router.get('/user-profiles/options', (req, res) => res.json({ data: database.list('profiles') }))
router.get('/user-manual', (req, res) => res.json({ data: database.setting('user-manual', { available: false, file_name: '' }) }))
router.post('/user-manual', upload.single('manual'), (req, res) => res.json({ data: database.setSetting('user-manual', { available: true, file_name: req.file?.originalname || 'user-manual', localOnly: true }) }))
router.get('/admin/me', (req, res) => res.json({ isAdmin: true, isSuperAdmin: true, role: 'super_admin', user: demoUser }))
router.get('/admin/column-permissions', (req, res) => res.json(database.setting('admin:column-permissions', { columns: {}, permissions: { clients: {}, candidates: {}, jobs: {} } })))
router.patch('/admin/column-permissions', (req, res) => {
  const current = database.setting('admin:column-permissions', { columns: {}, permissions: { clients: {}, candidates: {}, jobs: {} } })
  const permissions = { ...current.permissions, [req.body.tableName]: { ...(current.permissions?.[req.body.tableName] || {}), [req.body.columnKey]: req.body.accessMode } }
  res.json(database.setSetting('admin:column-permissions', { ...current, permissions }))
})
router.get('/admin/page-view-permissions', (req, res) => res.json(database.setting('admin:page-view-permissions', { permissions: {} })))
router.patch('/admin/page-view-permissions', (req, res) => {
  const current = database.setting('admin:page-view-permissions', { permissions: {} })
  const permissions = { ...current.permissions, [req.body.pageKey]: req.body.viewPermission }
  res.json(database.setSetting('admin:page-view-permissions', { permissions }))
})
router.get('/admin/dashboard-visibility', (req, res) => res.json(database.setting('admin:dashboard-visibility', { overall: true, restrictNonAdminToSelf: false })))
router.patch('/admin/dashboard-visibility', (req, res) => res.json(database.setSetting('admin:dashboard-visibility', { ...database.setting('admin:dashboard-visibility', {}), ...req.body })))
router.patch('/admin/consultant-report-visibility', (req, res) => res.json(database.setSetting('admin:consultant-report-visibility', { audience: req.body.audience || 'all' })))
router.get('/admin/bootstrap', (req, res) => res.json({ users: database.list('profiles'), permissions: database.setting('admin:page-view-permissions', {}).permissions || {}, columns: database.setting('admin:column-permissions', {}).columns || {} }))
router.get('/admin/users', (req, res) => res.json({ data: database.list('profiles') }))
router.post('/admin/users', (req, res) => res.status(201).json({ data: database.put('profiles', { id: req.body.user_id || crypto.randomUUID(), user_id: req.body.user_id, role: req.body.role || 'admin', status: 'active' }) }))
router.delete('/admin/users/:email', (req, res) => {
  const profile = database.list('profiles').find(row => row.email === req.params.email)
  return profile && profile.id !== demoUser.id ? res.json({ ok: database.remove('profiles', profile.id) }) : res.json({ ok: false })
})
router.patch('/admin/users/:email/role', (req, res) => {
  const profile = database.list('profiles').find(row => row.email === req.params.email)
  return profile ? res.json({ data: database.put('profiles', { ...profile, role: req.body.role || profile.role }) }) : res.status(404).json({ error: 'User not found' })
})
router.get('/admin/user-profiles', (req, res) => res.json({ data: database.list('profiles') }))
router.get('/admin/employees', (req, res) => res.json({ data: database.list('profiles') }))
router.get('/admin/employees/:id', (req, res) => {
  const employee = database.get('profiles', req.params.id)
  return employee ? res.json({ data: { employee, assignments: { clients: [], jobs: [], candidates: [] } } }) : res.status(404).json({ error: 'Employee not found' })
})
router.get('/admin/employees/:id/reassignment-records', (req, res) => res.json({ data: { rows: [], total: 0, offset: Number(req.query.offset || 0), limit: Number(req.query.limit || 50) } }))
router.patch('/admin/employees/:id/status', (req, res) => {
  const data = updateStored('profiles', req.params.id, { status: req.body.status })
  return data ? res.json({ data }) : res.status(404).json({ error: 'Employee not found' })
})
router.post('/admin/employees/:id/reassign', (req, res) => res.json({ data: { reassigned: 0, destination_user_id: req.body.destination_user_id } }))
router.get('/admin/locked-records', (req, res) => res.json({ data: database.list('record_locks') }))
router.patch('/admin/locks/:table/:id', (req, res) => res.json({ data: database.put('record_locks', { id: `${req.params.table}:${req.params.id}`, table_name: req.params.table, record_id: req.params.id, locked: Boolean(req.body.locked) }) }))
router.get('/admin/record-management/records', (req, res) => {
  const kind = ({ client: 'clients', candidate: 'candidates', job: 'jobs', mandate: 'jobs' })[req.query.entity] || req.query.entity
  res.json(page(database.list(kind || 'candidates'), req))
})
router.post('/admin/record-management/preview', (req, res) => res.json({ data: { entityType: req.body.entityType, ids: req.body.ids || [], deleteCount: (req.body.ids || []).length } }))
router.post('/admin/record-management/delete', (req, res) => {
  const kind = ({ client: 'clients', candidate: 'candidates', job: 'jobs', mandate: 'jobs' })[req.body.entityType] || req.body.entityType
  const deleted = (req.body.ids || []).filter(recordId => database.remove(kind, recordId)).length
  res.json({ data: { deleted } })
})

kindRoutes('clients', companyConfig.ids.clientPrefix, 'client_display_id')
kindRoutes('jobs', companyConfig.ids.jobPrefix, 'job_display_id')
kindRoutes('candidates', companyConfig.ids.candidatePrefix, 'candidate_display_id')

router.get('/clients/:id/follow-ups', (req, res) => res.json({ data: database.list('followups').filter(row => row.client_id === req.params.id) }))
router.post('/clients/:id/follow-ups', (req, res) => res.status(201).json({ data: database.put('followups', { ...req.body, client_id: req.params.id }) }))
router.patch('/clients/:id/follow-ups/:followUpId', (req, res) => {
  const data = updateStored('followups', req.params.followUpId, req.body)
  return data ? res.json({ data }) : res.status(404).json({ error: 'Follow-up not found' })
})
router.delete('/clients/:id/follow-ups/:followUpId', (req, res) => res.json({ ok: database.remove('followups', req.params.followUpId) }))
router.post('/clients/contract-uploads', upload.any(), (req, res) => res.json({ data: { path: `local-demo/${crypto.randomUUID()}-${req.files?.[0]?.originalname || 'contract'}`, localOnly: true } }))

router.get('/candidates/by-candidate/:candidateId/associations', (req, res) => res.json({ data: database.list('candidates').filter(row => row.candidateId === req.params.candidateId) }))
router.patch('/candidates/:id/status', (req, res) => {
  const record = database.get('candidates', req.params.id)
  if (!record) return res.status(404).json({ error: 'Candidate not found' })
  return res.json(database.put('candidates', { ...record, status: req.body.status, candidate_status: req.body.status }))
})
router.get('/candidates/check-duplicate', (req, res) => res.json({ duplicate: false, existing: null }))
router.post('/candidates/check-cv-duplicate', upload.any(), (req, res) => res.json({ duplicate: false }))
router.post('/resumes/bulk-parse', upload.array('resumes', 20), (req, res) => {
  const rows = (req.files || []).map(file => ({
    full_name: file.originalname.replace(/\.[^.]+$/, '').replaceAll(/[-_]+/g, ' '),
    candidate_name: file.originalname.replace(/\.[^.]+$/, '').replaceAll(/[-_]+/g, ' '),
    file_name: file.originalname,
    cv_storage_path: `local-demo/${crypto.randomUUID()}-${file.originalname}`,
    skills: [],
    parsing_note: 'Local demo mode extracted the name from the file name; AI/OCR is disabled.'
  }))
  res.json({ rows })
})
router.post('/resumes/discard-temp', (req, res) => res.json({ ok: true, discarded: Array.isArray(req.body.paths) ? req.body.paths.length : 0 }))
router.get('/resumes/open', (req, res) => res.status(404).json({ error: 'Local demo file previews are not persisted. Re-upload the document when needed.' }))
router.get('/documents/open/:type', (req, res) => res.status(404).json({ error: `Local ${req.params.type} preview is not available for this sample record.` }))
router.post('/candidates/ai-filter', (req, res) => res.json({ filters: null, message: 'AI filtering is disabled in local demo mode.' }))
router.post('/clients/ai-filter', (req, res) => res.json({ filters: null, message: 'AI filtering is disabled in local demo mode.' }))
router.post('/jobs/ai-filter', (req, res) => res.json({ filters: null, message: 'AI filtering is disabled in local demo mode.' }))
router.get('/jobs/users/options', (req, res) => res.json({ data: database.list('profiles') }))

router.get('/dashboard', (req, res) => {
  const clients = database.list('clients')
  const candidates = database.list('candidates')
  const jobs = database.list('jobs')
  const statusData = (values, statuses, selector) => statuses.map(name => ({ name, value: values.filter(row => selector(row) === name).length }))
  const candidateStages = companyConfig.pipeline.filter(stage => stage.enabled && stage.key !== 'duplicate').map(stage => stage.label)
  const recentActivity = [...clients.map(row => ({ date: row.updated_at, module: 'Client', text: `Client updated: ${row.client_name}`, actorName: demoUser.name, id: `client-${row.id}` })), ...jobs.map(row => ({ date: row.updated_at, module: 'Mandate', text: `Mandate updated: ${row.title}`, actorName: demoUser.name, id: `job-${row.id}` })), ...candidates.map(row => ({ date: row.updated_at, module: 'Candidate', text: `Candidate updated: ${row.full_name}`, actorName: demoUser.name, id: `candidate-${row.id}` }))].sort((a, b) => new Date(b.date) - new Date(a.date)).slice(0, 20)
  res.json({
    consultantOptions: [demoUser.name],
    kpis: { totalClients: clients.length, totalCandidates: candidates.length, pendingCandidates: candidates.filter(row => !/joined|hired/i.test(row.status)).length, totalMandates: jobs.length, activeClients: clients.filter(row => row.status === 'Active').length, placements: candidates.filter(row => /joined|hired/i.test(row.status)).length },
    clientStatusData: statusData(clients, companyConfig.clients.statuses, row => row.status),
    candidateStatusData: statusData(candidates, candidateStages, row => row.status),
    mandateStatusData: statusData(jobs, companyConfig.jobs.statuses, row => row.mandate_status),
    billingEntityData: companyConfig.billing.entities.map(entity => ({ label: `${entity.key} Billing Entity`, value: clients.filter(row => row.billing_entity === entity.key).length })),
    clientTrend: [], candidateTrend: [], mandateTrend: [],
    candidateFunnel: candidateStages.slice(0, 6).map(name => ({ name, value: candidates.filter(row => row.status === name).length })),
    consultantPerformance: [{ consultant: demoUser.name, candidates: candidates.length, mandates: jobs.length, placements: candidates.filter(row => /joined|hired/i.test(row.status)).length }],
    recentActivity, sectionErrors: {}, period: req.query.period || '', consultant: req.query.consultant || 'Overall (All Consultants)'
  })
})

router.get('/public/open-roles/count', (req, res) => res.json({ count: database.list('jobs').filter(row => row.is_public).length }))
router.get('/public/open-roles', (req, res) => res.json({ data: database.list('jobs').filter(row => row.is_public) }))
router.get('/public/open-roles/:slug', (req, res) => {
  const record = database.list('jobs').find(row => row.public_slug === req.params.slug)
  return record ? res.json({ data: record }) : res.status(404).json({ error: 'Role not found.' })
})
router.post('/public/applications', upload.any(), (req, res) => {
  database.put('applications', { ...body(req), status: 'New' })
  res.status(201).json({ success: true, message: 'Application submitted in local demo mode.' })
})
router.get('/applied-candidates/count', (req, res) => res.json({ count: database.count('applications') }))
router.get('/applied-candidates', (req, res) => res.json(page(database.list('applications'), req)))
router.get('/applied-candidates/:id', (req, res) => {
  const data = database.get('applications', req.params.id)
  return data ? res.json({ data }) : res.status(404).json({ error: 'Application not found' })
})
router.patch('/applied-candidates/:id/status', (req, res) => {
  const data = updateStored('applications', req.params.id, { status: req.body.status, rejection_reason: req.body.rejection_reason || '' })
  return data ? res.json({ data }) : res.status(404).json({ error: 'Application not found' })
})
router.post('/applied-candidates/:id/convert', (req, res) => {
  const application = database.get('applications', req.params.id)
  if (!application) return res.status(404).json({ error: 'Application not found' })
  const job = database.get('jobs', req.body.job_id || application.job_id)
  const candidate = database.put('candidates', {
    ...application,
    ...req.body,
    id: crypto.randomUUID(),
    associationId: crypto.randomUUID(),
    candidateId: crypto.randomUUID(),
    candidate_display_id: database.displayId(companyConfig.ids.candidatePrefix, 'candidates'),
    full_name: application.full_name || application.name || application.candidate_name,
    status: req.body.status || companyConfig.pipeline.find(stage => stage.enabled)?.label || 'Interested',
    job_id: job?.id || '',
    job_title: job?.title || ''
  })
  database.put('applications', { ...application, status: 'Converted', converted_candidate_id: candidate.id })
  res.json({ data: candidate })
})
router.get('/applied-candidates/:id/cv', (req, res) => res.status(404).json({ error: 'This sample application does not include a local CV file.' }))

router.get('/presence', (req, res) => res.json({ data: [{ user_id: demoUser.id, name: demoUser.name, email: demoUser.email, online: true }], tabs: [], cutoff: new Date().toISOString() }))
router.post('/presence/heartbeat', (req, res) => res.json({ ok: true, last_seen_at: new Date().toISOString() }))
router.post('/presence/offline', (req, res) => res.json({ ok: true }))
router.get('/notifications', (req, res) => res.json({ data: [], unreadCount: 0, hasMore: false }))
router.patch('/notifications/:id/read', (req, res) => res.json({ success: true }))
router.delete('/notifications/read', (req, res) => res.json({ success: true, cleared: 0 }))

router.get('/user-preferences/:key', (req, res) => res.json({ data: { key: req.params.key, value: database.setting(`preference:${req.params.key}`, []) } }))
router.put('/user-preferences/:key', (req, res) => res.json({ data: { key: req.params.key, value: database.setSetting(`preference:${req.params.key}`, req.body.value) } }))

router.get('/attendance/permissions', (req, res) => res.json({ data: { can_manage: true, can_approve: true, can_view_team: true } }))
router.put('/attendance/permissions', (req, res) => res.json({ data: database.setSetting('attendance:permissions', req.body) }))
router.get('/attendance/today', (req, res) => res.json({ data: database.setting('attendance:today', { clock_in: null, clock_out: null, status: 'Not clocked in' }) }))
router.post('/attendance/clock-in', (req, res) => res.json({ data: database.setSetting('attendance:today', { clock_in: new Date().toISOString(), clock_out: null, status: 'Present' }) }))
router.post('/attendance/clock-out', (req, res) => { const current = database.setting('attendance:today', {}); res.json({ data: database.setSetting('attendance:today', { ...current, clock_out: new Date().toISOString(), status: 'Present' }) }) })
router.get('/attendance/month', (req, res) => res.json({ data: { records: [], summary: { present: 0, absent: 0, leave: 0, workingDays: 0 } } }))
router.get('/attendance/balance', (req, res) => res.json({ data: { available: companyConfig.attendance.annualLeaveAllowance, used: 0, pending: 0 } }))
router.get('/attendance/leave', (req, res) => res.json({ data: database.list('leave_requests') }))
router.post('/attendance/leave', (req, res) => res.json({ data: database.put('leave_requests', { ...req.body, status: 'pending' }) }))
router.post('/attendance/leave/preview', (req, res) => res.json({ data: { ...req.body, available: companyConfig.attendance.annualLeaveAllowance, valid: true } }))
router.post('/attendance/leave/:id/cancel', (req, res) => { const data = updateStored('leave_requests', req.params.id, { status: 'cancelled' }); return data ? res.json({ data }) : res.status(404).json({ error: 'Leave request not found' }) })
router.post('/attendance/leave/:id/review', (req, res) => { const data = updateStored('leave_requests', req.params.id, { status: req.body.decision, review_note: req.body.note || '' }); return data ? res.json({ data }) : res.status(404).json({ error: 'Leave request not found' }) })
router.get('/attendance/corrections', (req, res) => res.json({ data: database.list('corrections') }))
router.post('/attendance/corrections', (req, res) => res.json({ data: database.put('corrections', { ...req.body, status: 'pending' }) }))
router.post('/attendance/corrections/:id/cancel', (req, res) => { const data = updateStored('corrections', req.params.id, { status: 'cancelled' }); return data ? res.json({ data }) : res.status(404).json({ error: 'Correction not found' }) })
router.post('/attendance/corrections/:id/review', (req, res) => { const data = updateStored('corrections', req.params.id, { status: req.body.decision, review_note: req.body.note || '' }); return data ? res.json({ data }) : res.status(404).json({ error: 'Correction not found' }) })
router.get('/attendance/holidays', (req, res) => res.json({ data: database.list('holidays') }))
router.post('/attendance/holidays', (req, res) => res.status(201).json({ data: database.put('holidays', req.body) }))
router.delete('/attendance/holidays/:id', (req, res) => res.json({ data: { deleted: database.remove('holidays', req.params.id) } }))
router.get('/attendance/team', (req, res) => res.json({ data: [] }))
router.get('/attendance/leave-balances', (req, res) => res.json({ data: [] }))
router.post('/attendance/leave-balances/:id/adjust', (req, res) => res.json({ data: database.put('leave_adjustments', { ...req.body, user_id: req.params.id }) }))

router.get('/performance/permissions', (req, res) => res.json({ permissions: { can_edit: true, can_manage: true } }))
router.put('/performance/permissions', (req, res) => res.json({ permissions: database.setSetting('performance:permissions', req.body.permissions || {}) }))
router.get('/performance/completion-statuses', (req, res) => res.json({ data: [] }))
router.get('/performance/me', (req, res) => res.json({ data: { employee_user_id: demoUser.id, rows: database.setting('performance:demo-admin', []) } }))
router.get('/performance/handbook', (req, res) => res.json({ data: database.setting('performance:handbook', { available: false, file_name: '' }) }))
router.post('/performance/handbook', upload.single('handbook'), (req, res) => res.json({ data: database.setSetting('performance:handbook', { available: true, file_name: req.file?.originalname || 'handbook', localOnly: true }) }))
router.get('/performance/:employeeUserId', (req, res) => res.json({ data: { employee_user_id: req.params.employeeUserId, rows: database.setting(`performance:${req.params.employeeUserId}`, []) } }))
router.put('/performance/:employeeUserId', (req, res) => res.json({ data: database.setSetting(`performance:${req.params.employeeUserId}`, req.body.rows || []) }))

router.get('/reports/consultant/options', (req, res) => res.json({ data: { options: [{ key: demoUser.id, name: demoUser.name, email: demoUser.email, employeeStatus: 'Active' }, { key: 'overall', name: 'Overall', email: '', employeeStatus: 'Active' }], defaultConsultantKey: demoUser.id } }))
router.get('/reports/consultant/export-preview', (req, res) => {
  const rows = ['Type,Name,Status', ...database.list('jobs').map(row => `Mandate,"${String(row.title || '').replaceAll('"', '""')}","${row.status || ''}"`)]
  res.json({ data: { contentBase64: Buffer.from(rows.join('\n')).toString('base64'), mimeType: 'text/csv', fileName: `${companyConfig.slug}-consultant-report.csv` } })
})
router.get('/reports/consultant/mandates', (req, res) => res.json({ data: { rows: database.list('jobs'), pagination: { page: Number(req.query.page || 1), pageSize: Number(req.query.page_size || 25), total: database.count('jobs'), totalPages: 1 } } }))
router.get('/reports/consultant/conversions', (req, res) => res.json({ data: { rows: database.list('jobs').map(row => ({ ...row, ageDays: 0, conversionDays: 0 })), pagination: { page: Number(req.query.page || 1), pageSize: Number(req.query.page_size || 25), total: database.count('jobs'), totalPages: 1 } } }))
router.get('/reports/consultant', (req, res) => {
  const candidates = database.list('candidates')
  const jobs = database.list('jobs')
  const statuses = Object.fromEntries(companyConfig.pipeline.filter(stage => stage.enabled).map(stage => [stage.label, candidates.filter(row => row.status === stage.label).length]))
  const startDate = req.query.start_date || new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().slice(0, 10)
  const endDate = req.query.end_date || new Date().toISOString().slice(0, 10)
  res.json({ data: {
    meta: { startDate, endDate, generatedAt: new Date().toISOString(), generatedBy: demoUser.name },
    consultant: { key: req.query.scope === 'overall' ? 'overall' : demoUser.id, name: req.query.scope === 'overall' ? 'Overall' : demoUser.name, email: demoUser.email, isOverall: req.query.scope === 'overall' },
    mandateSummary: { total: jobs.length, p1: jobs.filter(row => /P1/i.test(row.status)).length, p2: jobs.filter(row => /P2/i.test(row.status)).length, p3: jobs.filter(row => /P3/i.test(row.status)).length, completed: jobs.filter(row => /complete/i.test(row.status)).length, scrapped: jobs.filter(row => /scrap/i.test(row.status)).length },
    recentMandates: jobs.slice(0, 5), recentConversions: jobs.slice(0, 5), conversionSummary: [],
    candidateOverview: { total: candidates.length, counts: statuses },
    candidatePipeline: Object.entries(statuses).map(([label, value]) => ({ key: label.toLowerCase().replaceAll(/\W+/g, '_'), label, value })),
    dailyCandidateUploads: candidates.map(row => ({ date: String(row.created_at).slice(0, 10), candidateCount: 1 })),
    attendance: { available: true, metrics: [] }, attendanceBreakdown: [], exceptions: [], positiveOutcomes: []
  } })
})

router.get('/invoice/entities', (req, res) => {
  const invoices = database.list('invoices')
  res.json({ data: database.list('invoice_entities'), invoices, totals: aggregateTaxInvoiceTotals(invoices) })
})
router.post('/invoice/entities', (req, res) => res.status(201).json({ data: database.put('invoice_entities', { ...req.body, entity_display_id: `EID${database.count('invoice_entities') + 1}`, invoice_id: `EID${database.count('invoice_entities') + 1}` }) }))
router.get('/invoice/entities/:id', (req, res) => {
  const entity = database.get('invoice_entities', req.params.id)
  return entity ? res.json({ data: { entity, invoices: database.list('invoices').filter(row => row.invoice_entity_id === entity.id) } }) : res.status(404).json({ error: 'Entity not found' })
})
router.put('/invoice/entities/:id', (req, res) => { const data = updateStored('invoice_entities', req.params.id, req.body); return data ? res.json({ data }) : res.status(404).json({ error: 'Entity not found' }) })
router.delete('/invoice/entities/:id', (req, res) => res.json({ ok: database.remove('invoice_entities', req.params.id) }))
router.get('/invoice/next-number', (req, res) => {
  const invoiceNumber = localInvoiceNumber(req.query.billing_entity, req.query.invoice_type, req.query.invoice_date)
  res.json({ invoiceNumber, invoice_number: invoiceNumber })
})
router.post('/invoice/preview', async (req, res) => { try { res.json(await localInvoiceResult(req.body)) } catch (error) { res.status(400).json({ error: error.message }) } })
router.post('/invoice/generate', async (req, res) => { try { res.status(201).json(await localInvoiceResult(req.body, { persist: true })) } catch (error) { res.status(400).json({ error: error.message }) } })
router.post('/invoice/commit-preview', async (req, res) => { try { res.status(201).json(await localInvoiceResult(req.body, { persist: true })) } catch (error) { res.status(400).json({ error: error.message }) } })
router.post('/invoice/entities/:entityId/invoices/:id/cancel', (req, res) => { const data = updateStored('invoices', req.params.id, { status: 'cancelled', cancelled_at: new Date().toISOString() }); return data ? res.json({ data }) : res.status(404).json({ error: 'Invoice not found' }) })
router.get('/invoice/invoices/:id/reassignment-number', (req, res) => { const invoice = database.get('invoices', req.params.id); if (!invoice) return res.status(404).json({ error: 'Invoice not found' }); const invoiceNumber = localInvoiceNumber(invoice.billing_entity, invoice.invoice_type, req.query.invoice_date || invoice.invoice_date); return res.json({ data: { invoice_number: invoiceNumber } }) })
router.post('/invoice/invoices/:id/regeneration-preview', async (req, res) => { try { const current = database.get('invoices', req.params.id); if (!current) return res.status(404).json({ error: 'Invoice not found' }); res.json(await localInvoiceResult({ ...current, ...req.body, id: current.id })) } catch (error) { res.status(400).json({ error: error.message }) } })
router.put('/invoice/invoices/:id/regenerate', async (req, res) => { try { const current = database.get('invoices', req.params.id); if (!current) return res.status(404).json({ error: 'Invoice not found' }); res.json(await localInvoiceResult({ ...current, ...req.body, id: current.id }, { persist: true })) } catch (error) { res.status(400).json({ error: error.message }) } })
router.delete('/invoice/invoice-pdf-versions/:id', (req, res) => res.json({ ok: true }))
router.post('/gst/lookup', (req, res) => res.status(404).json({ error: 'Live GST lookup is disabled locally. Enter the details manually.', fallback: true }))

router.post('/local/reset', (req, res) => { database.reset(); res.json({ ok: true }) })
router.get('/local/info', (req, res) => res.json({ runtime: 'local-demo', database: database.databasePath, user: demoUser }))

router.use((req, res) => res.status(501).json({ error: `This feature is not available in local demo mode yet: ${req.method} ${req.originalUrl}` }))

module.exports = router
